// Generated by CoffeeScript 1.7.1
(function() {
  var Scene,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Scene = (function() {
    function Scene(container) {
      this.animate = __bind(this.animate, this);
      this.onresize = __bind(this.onresize, this);
      var $container, ambientLight, auxLight, camera, controls, effect, height, mainLight, renderer, scene, time, width;
      time = Date.now();
      $container = $(container);
      width = $container.width();
      height = $container.height();
      scene = new THREE.Scene();
      camera = new THREE.PerspectiveCamera(60, width / height, 0.001, 100000);
      camera.position.set(0, 0, 0);
      camera.lookAt(new THREE.Vector3());
      scene.add(camera);
      renderer = new THREE.WebGLRenderer({
        antialias: true
      });
      renderer.setSize(width, height);
      renderer.setClearColor(0x000000, 1);
      renderer.autoClear = false;
      $container.append(renderer.domElement);
      effect = new THREE.VREffect(renderer);
      controls = new THREE.VRControls(camera);
      ambientLight = new THREE.AmbientLight(0x222222);
      scene.add(ambientLight);
      mainLight = new THREE.DirectionalLight(0xffffff, 0.8);
      mainLight.position.set(1, 2, 4).normalize();
      scene.add(mainLight);
      auxLight = new THREE.DirectionalLight(0xffffff, 0.3);
      auxLight.position.set(-4, -1, -2).normalize();
      scene.add(auxLight);
      camera.position.add(new THREE.Vector3(8, 6, 15));
      $(window).resize(this.onresize);
      this.time = time;
      this.$container = $container;
      this.camera = camera;
      this.scene = scene;
      this.renderer = renderer;
      this.effect = effect;
      this.controls = controls;
    }

    Scene.prototype.onresize = function() {
      var height, width, _ref;
      _ref = [this.$container.width(), this.$container.height()], width = _ref[0], height = _ref[1];
      this.camera.aspect = width / height;
      this.camera.updateProjectionMatrix();
      return this.renderer.setSize(width, height);
    };

    Scene.prototype.add = function(object) {
      return this.scene.add(object);
    };

    Scene.prototype.remove = function(object) {
      return this.scene.remove(object);
    };

    Scene.prototype.animate = function(callback) {
      requestAnimationFrame((function(_this) {
        return function() {
          return _this.animate(callback);
        };
      })(this));
      if (typeof callback === "function") {
        callback();
      }
      if (1.) {
        this.controls.update();
        this.effect.render(this.scene, this.camera);
      } else {
        this.renderer.clear();
        this.renderer.render(this.scene, this.camera);
      }
      return this.time = Date.now();
    };

    return Scene;

  })();

  this.Scene = Scene;

}).call(this);
